// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiSDzwg8IU_12Jagrat8pQg0KC1K2LnA',
    appId: '1:1049876705882:web:a2fa6c7e322f245e965e63',
    messagingSenderId: '1049876705882',
    projectId: 'fp-ppb-c6',
    authDomain: 'fp-ppb-c6.firebaseapp.com',
    storageBucket: 'fp-ppb-c6.firebasestorage.app',
    measurementId: 'G-CG5RSFPKF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmVjVwbb-J2Pw933780n6y3EZAb-14Uo',
    appId: '1:1049876705882:android:bb17d2ddb070ece7965e63',
    messagingSenderId: '1049876705882',
    projectId: 'fp-ppb-c6',
    storageBucket: 'fp-ppb-c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1PigIq_benjlpq_BYBXWzS67eP1uIXYk',
    appId: '1:1049876705882:ios:df94156d58669342965e63',
    messagingSenderId: '1049876705882',
    projectId: 'fp-ppb-c6',
    storageBucket: 'fp-ppb-c6.firebasestorage.app',
    iosBundleId: 'com.example.splitBillApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1PigIq_benjlpq_BYBXWzS67eP1uIXYk',
    appId: '1:1049876705882:ios:df94156d58669342965e63',
    messagingSenderId: '1049876705882',
    projectId: 'fp-ppb-c6',
    storageBucket: 'fp-ppb-c6.firebasestorage.app',
    iosBundleId: 'com.example.splitBillApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwiSDzwg8IU_12Jagrat8pQg0KC1K2LnA',
    appId: '1:1049876705882:web:f03e3996740ad51c965e63',
    messagingSenderId: '1049876705882',
    projectId: 'fp-ppb-c6',
    authDomain: 'fp-ppb-c6.firebaseapp.com',
    storageBucket: 'fp-ppb-c6.firebasestorage.app',
    measurementId: 'G-TLJNRNDEYC',
  );

}