// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWjRmB9Etwbxd_yk1_RWMJO4oxz4Sjok',
    appId: '1:732168305309:web:138e97c45c3c15be5a7274',
    messagingSenderId: '732168305309',
    projectId: 'fp-ppb-add06',
    authDomain: 'fp-ppb-add06.firebaseapp.com',
    storageBucket: 'fp-ppb-add06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTnErOL422SfaLiet4DGJTndD0Rw4wY8',
    appId: '1:732168305309:android:6cdc467243175f995a7274',
    messagingSenderId: '732168305309',
    projectId: 'fp-ppb-add06',
    storageBucket: 'fp-ppb-add06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0nPNl9W0awu7ppQm8RPr3ur4YieAD4A',
    appId: '1:732168305309:ios:b6a0cd144378af175a7274',
    messagingSenderId: '732168305309',
    projectId: 'fp-ppb-add06',
    storageBucket: 'fp-ppb-add06.firebasestorage.app',
    iosBundleId: 'com.example.splitBillApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0nPNl9W0awu7ppQm8RPr3ur4YieAD4A',
    appId: '1:732168305309:ios:b6a0cd144378af175a7274',
    messagingSenderId: '732168305309',
    projectId: 'fp-ppb-add06',
    storageBucket: 'fp-ppb-add06.firebasestorage.app',
    iosBundleId: 'com.example.splitBillApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqWjRmB9Etwbxd_yk1_RWMJO4oxz4Sjok',
    appId: '1:732168305309:web:535eeed197ff12355a7274',
    messagingSenderId: '732168305309',
    projectId: 'fp-ppb-add06',
    authDomain: 'fp-ppb-add06.firebaseapp.com',
    storageBucket: 'fp-ppb-add06.firebasestorage.app',
  );
}
